export type ThemeType = "glassmorphic" | "neumorphic" | "modern";

export const themes: Record<ThemeType, any> = {
  glassmorphic: {
    background: "from-blue-900/20 to-purple-900/20",
    card: "bg-black/25 backdrop-blur-md border border-white/20",
    textPrimary: "text-white",
    textSecondary: "text-gray-300",
    accent: "blue-400",
    shadow: "shadow-lg",
    buttonBg: "bg-blue-500",
    buttonText: "text-white",
    fontFamily: "Inter, sans-serif",
    fontSize: "1rem",
    borderRadius: "1.5rem",
    primaryColor: "#3b82f6",
    secondaryColor: "#10b981",
    surfaceColor: "rgba(0,0,0,0.25)",
    backgroundColor: "rgba(59, 130, 246, 0.1)",
  },
  neumorphic: {
    background: "from-gray-100 to-gray-200",
    card: "bg-gray-100 shadow-inner border border-gray-200",
    textPrimary: "text-gray-900",
    textSecondary: "text-gray-600",
    accent: "blue-500",
    shadow: "shadow-md",
    buttonBg: "bg-blue-600",
    buttonText: "text-white",
    fontFamily: "Poppins, sans-serif",
    fontSize: "1rem",
    borderRadius: "1rem",
    primaryColor: "#2563eb",
    secondaryColor: "#059669",
    surfaceColor: "#f3f4f6",
    backgroundColor: "#f9fafb",
  },
  modern: {
    background: "from-white to-gray-50",
    card: "bg-white shadow-lg border border-gray-100",
    textPrimary: "text-gray-900",
    textSecondary: "text-gray-600",
    accent: "purple-500",
    shadow: "shadow-lg",
    buttonBg: "bg-purple-600",
    buttonText: "text-white",
    fontFamily: "Roboto, sans-serif",
    fontSize: "1rem",
    borderRadius: "0.75rem",
    primaryColor: "#9333ea",
    secondaryColor: "#06b6d4",
    surfaceColor: "#ffffff",
    backgroundColor: "#f8fafc",
  },
};
